
// The [throw] slot in Hyperlambda is used to raise an exception with a specified message. When invoked, it interrupts the normal flow of execution, allowing the error to be caught and handled by a [.catch] block if present. If the [public] parameter is set to true, the exception message is propagated to the client, even in release builds, unless a [.catch] block intercepts it.
throw:x:-
