
// The code demonstrates the use of a [try] block in Hyperlambda to handle exceptions. Within the [try] block, a [throw] slot is used to raise an exception with a specified message "Whatever". This setup allows for the potential handling of the exception in a subsequent [.catch] block, although the [.catch] block is not shown here.
try
   throw:Whatever
