/*
 * This Hyperlambda snippet demonstrates how to use the [throw] slot to raise an exception with a custom message.
 * The [throw] slot is used to simulate an error condition by raising an exception that can be caught using a [try] block.
 *
 * 1. [throw]
 *    * Raises an exception with the message "Custom error occurred".
 *    * This demonstrates how to trigger an error within Hyperlambda code.
 */
throw:Custom error occurred
