/*
 * Use [try] to catch and log a thrown error
 */

try
   throw:Something went wrong
.catch
   log.error:x:@.exception/*/message
